all:
    hosts:
        mail.example.com:
    children:
        webservers:
        hosts:
            foo.example.com:
            bar.example.com:
    dbservers:
        hosts:
            one.example.com:
            two.example.com:
            three.example.com:
