---
- hosts: web-servers
  become: true
  gather_facts: yes
  name: setup nginx web server
  serial: 10
  roles:
  # install and configure nginx service
    - { role: nginx, become: True, tags: setup_nginx }