apiVersion: v1
kind: Pod
metadata:
  name: test-emptydir
spec:
  containers:
  - image: ahmadrafiee/mecan-sample-app:ver1
    name: test-container
    resources:
      requests:
        memory: 10Mi
        cpu: 10m
      limits:
        memory: 20Mi
        cpu: 20m
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi
