apiVersion: v1
kind: Pod
metadata:
  name: test-host-path
spec:
  containers:
  - image: busybox
    name: test-host-path-container
    command: ['sh', '-c', 'sleep 3600']
    resources:
      requests:
        memory: 10Mi
        cpu: 10m
      limits:
        memory: 20Mi
        cpu: 20m
    volumeMounts:
    - mountPath: /opt/
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /etc/kubernetes/pki/
      # this field is optional
      type: Directory
