networks:
  web_net:
    external: true
    name: web_net
  app_net:
    external: true
    name: app_net

volumes:
  nexus_data:
    name: nexus_data

services:
  nexus:
    image: sonatype/nexus3:${NEXUS_IMAGE_TAG}
    container_name: nexus
    hostname: ${HOSTNAME}
    restart: ${RESTART_POLICY}
    volumes:
      - nexus_data:/nexus-data
    networks:
      - web_net
      - app_net

    # Congig for traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net
      - traefik.http.routers.repo.entrypoints=http
      - traefik.http.routers.repo.rule=Host(`${NEXUS_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.repo.service=repo-secure
      - traefik.http.routers.repo.middlewares=https-redirect
      - traefik.http.routers.repo-secure.entrypoints=https
      - traefik.http.routers.repo-secure.rule=Host(`${NEXUS_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.repo-secure.tls=true
      - traefik.http.routers.repo-secure.tls.options=default
      - traefik.http.routers.repo-secure.service=repo-secure
      - traefik.http.routers.repo-secure.tls.certresolver=mycert
      - traefik.http.services.repo-secure.loadbalancer.server.port=8081
      - traefik.http.routers.hubdocker.entrypoints=http
      - traefik.http.routers.hubdocker.rule=Host(`${HUB_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.hubdocker.middlewares=https-redirect
      - traefik.http.routers.hubdocker-secure.entrypoints=https
      - traefik.http.routers.hubdocker.service=hubdocker-secure
      - traefik.http.routers.hubdocker-secure.rule=Host(`${HUB_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.hubdocker-secure.tls=true
      - traefik.http.routers.hubdocker-secure.tls.options=default
      - traefik.http.routers.hubdocker-secure.service=hubdocker-secure
      - traefik.http.routers.hubdocker-secure.tls.certresolver=mycert
      - traefik.http.services.hubdocker-secure.loadbalancer.server.port=8082
      - traefik.http.routers.registry.entrypoints=http
      - traefik.http.routers.registry.rule=Host(`${REGISTRY_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.registry.middlewares=https-redirect
      - traefik.http.routers.registry-secure.entrypoints=https
      - traefik.http.routers.registry.service=registry-secure
      - traefik.http.routers.registry-secure.rule=Host(`${REGISTRY_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.registry-secure.tls=true
      - traefik.http.routers.registry-secure.tls.options=default
      - traefik.http.routers.registry-secure.service=registry-secure
      - traefik.http.routers.registry-secure.tls.certresolver=mycert
      - traefik.http.services.registry-secure.loadbalancer.server.port=8083
      - traefik.http.routers.quay.entrypoints=http
      - traefik.http.routers.quay.rule=Host(`${QUAY_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.quay.middlewares=https-redirect
      - traefik.http.routers.quay-secure.entrypoints=https
      - traefik.http.routers.quay.service=quay-secure
      - traefik.http.routers.quay-secure.rule=Host(`${QUAY_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.quay-secure.tls=true
      - traefik.http.routers.quay-secure.tls.options=default
      - traefik.http.routers.quay-secure.service=quay-secure
      - traefik.http.routers.quay-secure.tls.certresolver=mycert
      - traefik.http.services.quay-secure.loadbalancer.server.port=8084
      - traefik.http.routers.k8s.entrypoints=http
      - traefik.http.routers.k8s.rule=Host(`${K8S_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.k8s.middlewares=https-redirect
      - traefik.http.routers.k8s-secure.entrypoints=https
      - traefik.http.routers.k8s.service=k8s-secure
      - traefik.http.routers.k8s-secure.rule=Host(`${K8S_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.k8s-secure.tls=true
      - traefik.http.routers.k8s-secure.tls.options=default
      - traefik.http.routers.k8s-secure.service=k8s-secure
      - traefik.http.routers.k8s-secure.tls.certresolver=mycert
      - traefik.http.services.k8s-secure.loadbalancer.server.port=8085
      - traefik.http.routers.github.entrypoints=http
      - traefik.http.routers.github.rule=Host(`${GITHUB_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.github.middlewares=https-redirect
      - traefik.http.routers.github-secure.entrypoints=https
      - traefik.http.routers.github.service=github-secure
      - traefik.http.routers.github-secure.rule=Host(`${GITHUB_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.github-secure.tls=true
      - traefik.http.routers.github-secure.tls.options=default
      - traefik.http.routers.github-secure.service=github-secure
      - traefik.http.routers.github-secure.tls.certresolver=mycert
      - traefik.http.services.github-secure.loadbalancer.server.port=8086