---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo
          args:
            - "-text=Hello from app"
            - "-listen=:8080"
          ports:
            - containerPort: 8080