apiVersion: v1
kind: Secret
metadata:
  name: registry-login
  namespace: {{ .Values.spec.destination.namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.spec.registry.username }}
  password: {{ .Values.spec.registry.password }}