apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.imagePullSecrets.username | b64enc | quote }}
  password: {{ .Values.imagePullSecrets.password | b64enc | quote }}
