apiVersion: v1
kind: Namespace
metadata:
  name: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  label:
    argocd.argoproj.io/instance: app-of-apps-gustbook
---
apiVersion: v1
kind: Namespace
metadata:
  name: kustomize-guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  label:
    argocd.argoproj.io/instance: app-of-apps-gustbook
---
apiVersion: v1
kind: Namespace
metadata:
  name: helm-guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  label:
    argocd.argoproj.io/instance: app-of-apps-gustbook
