apiVersion: 1
datasources:
- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  editable: true
  isDefault: false
  jsonData:
    timeInterval: 15s
    httpHeaderName1: Connection
    httpHeaderName2: Upgrade
  secureJsonData:
    httpHeaderValue1: Upgrade
    httpHeaderValue2: websocket