apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa
---
apiVersion: v1
kind: Pod
metadata:
  name: vault-test
spec:
  serviceAccountName: myapp-sa
  containers:
  - name: app
    image: alpine:3.19
    command: ["sh", "-c", "sleep 3600"]
    env:
    - name: VAULT_ADDR
      value: "http://172.17.0.2:8200"   # Vault IP reachable from pod
