global:
  scrape_interval: 10s

scrape_configs:
- job_name: vmagent
  static_configs:
  - targets:
    - vmagent:8429

- job_name: vmalert
  static_configs:
  - targets:
    - vmalert:8880
    
- job_name: vmauth
  static_configs:
  - targets:
    - vmauth:8427

- job_name: vminsert
  static_configs:
  - targets:
    - vminsert-1:8480
    - vminsert-2:8480

- job_name: vmselect
  static_configs:
  - targets:
    - vmselect-1:8481
    - vmselect-2:8481

- job_name: vmstorage
  static_configs:
  - targets:
    - vmstorage-1:8482
    - vmstorage-2:8482

- job_name: 'grafana'
  scrape_interval: 30s
  metrics_path: '/metrics'
  static_configs:
    - targets: ['grafana:3000']

- job_name: 'alertmanager'
  scrape_interval: 30s
  metrics_path: '/metrics'
  static_configs:
    - targets: ['alertmanager:9093']

- job_name: 'cadvisor'
  static_configs:
    - targets: ['cadvisor:8080']

- job_name: 'node-exporter'
  static_configs:
    - targets: ['node-exporter:9100']

- job_name: 'blackbox_exporter'
  static_configs:
    - targets: ['blackbox-exporter:9115']

- job_name: 'blackbox-ping'
  scrape_interval: 30s
  metrics_path: /probe
  params:
    module: [icmp_ipv4]
  static_configs:
    - targets:
        - 8.8.8.8
        - google.com
        - node-exporter
        - blackbox-exporter
        - cadvisor
        - alertmanager
        - grafana
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115

- job_name: 'traefik'
  metrics_path: '/metrics'
  static_configs:
    - targets: ['traefik:8082']