apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://victoriametrics:8428
  orgId: 1
  basicAuth: false
  isDefault: true
  editable: true
  jsonData:
    prometheusType: Prometheus
    prometheusVersion: 2.24.0
    httpMethod: GET