apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-test
  labels:
    app: myapp-test-ds
  annotations:
    kubernetes.io/change-cause: ver1
spec:
  selector:
    matchLabels:
      app: myapp-test-ds
  template:
    metadata:
      labels:
        app: myapp-test-ds
        svc: example
    spec:
      nodeSelector:
        node: primary
      containers:
        - name: myapp-test
          image: ahmadrafiee/mecan-sample-app:ver1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m