apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts/
    targetRevision: main
    path: velero
    helm:
      valueFiles:
        - {{ .Values.spec.source.velero_variables_file }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
