apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  ports:
  - name: "result-service"
    port: 8081
    targetPort: 80
  selector:
    app: result
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      imagePullSecrets:
      - name: registry-login
      containers:
      - image: registry.mecan.ir/devops_certification/kubernetes/voting-app/result:v0.1.0
        name: result
        ports:
        - containerPort: 80
          name: result
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    certmanager.k8s.io/acme-http01-edit-in-place: "false"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: result-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: result.kube.mecan.ir
    http:
      paths:
      - backend:
          service:
            name: result
            port:
              number: 8081
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - result.kube.mecan.ir
    secretName: result-tls-secret