apiVersion: v1
entries:
  voting-app:
  - apiVersion: v2
    appVersion: "1.0"
    description: A Helm chart for the example voting app
    digest: eb288e7766f7791ae68eef9e42e49ae39dad7b38d2d3e2b0ed7e1cae3e47b36e
    name: voting-app
    urls:
    - voting-app-0.1.6.tgz
    version: 0.1.6
    maintainers:
      - name: "Ahmad Rafiee"
        email: "ahmad@dockerme.ir"