apiVersion: v1
entries:
  voting-app:
  - apiVersion: v2
    appVersion: "1.0"
    description: A Helm chart for the example voting app
    digest: 39f3e66fabae76e874ef4e8d9cc938d7ff17726df4a3b843482b06798566eb06
    name: voting-app
    urls:
    - voting-app-0.1.3.tgz
    version: 0.1.3
    home: https://github.com/AhmadRafiee/DevOps_Certification
    sources:
      - https://github.com/AhmadRafiee/DevOps_Certification
    maintainers:
      - name: "Ahmad Rafiee"
        email: "ahmad@dockerme.ir"