apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-addons-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AhmadRafiee/DevOps_Certification.git
    targetRevision: HEAD
    path: argocd/k8s-addons-app/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
