apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-username: {{ .Values.database.username | b64enc | quote }}
  postgres-password: {{ .Values.database.password | b64enc | quote }}
  postgres-database: {{ .Values.database.database | b64enc | quote }}