apiVersion: v1
kind: Service
metadata:
  name: voting-app-redis
  labels:
    app: voting-app
    component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: voting-app
    component: redis
