apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-frontend
  labels:
    app: voting-app
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: voting-app
      component: frontend
  template:
    metadata:
      labels:
        app: voting-app
        component: frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: 80
