apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  backupSyncPeriod: 2m0s
  provider: aws
  objectStorage:
    bucket: mecan-backup
  credential:
    name: velero-credential
    key: cloud
  config:
    region: minio
    profile: "default"
    s3ForcePathStyle: "true"
    s3Url: https://object.kube.mecan.ir/
---
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  credential:
    name: velero-credential
    key: cloud
  config:
    region: minio
    profile: "default"
