mode: standalone

image:
  repository: quay.io/minio/minio
  tag: RELEASE.2025-01-20T14-49-07Z
  pullPolicy: IfNotPresent

mountPath: "/data"

resources:
  requests:
    memory: 1G
    cpu: 500m
  limits:
    memory: 5G
    cpu: 1000m

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 50Gi

service:
  name: minio
  type: ClusterIP
  port: 9000

consoleService:
  name: minio-console
  type: ClusterIP
  port: 9001

extraArgs:
  - --console-address
  - :9001

environment:
  MINIO_SERVER_URL: "https://${minio_api_domain}"
  MINIO_BROWSER_REDIRECT_URL: "https://${minio_console_domain}"

consoleIngress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    certmanager.k8s.io/acme-http01-edit-in-place: "false"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  path: /
  hosts:
    - ${minio_console_domain}
  tls:
    - secretName: minio-console-example-tls
      hosts:
        - ${minio_console_domain}

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    certmanager.k8s.io/acme-http01-edit-in-place: "false"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  path: /
  hosts:
    - ${minio_api_domain}
  tls:
    - secretName: minio-example-tls
      hosts:
        - ${minio_api_domain}