apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: sahand
            server: "https://vip.sahand.mecan.ir:6443"
          - cluster: dena
            server: "https://vip.dena.mecan.ir:6443"
  template:
    metadata:
      name: "{{.cluster}}-addons"
    spec:
      project: default
      source:
        repoURL: "{{.repoURL}}"
        chart: "{{.chart}}"
        targetRevision: "{{.version}}"
        helm:
          valueFiles:
            - "{{.valuesPath}}/{{.cluster}}/{{.chart}}-values.yaml"
      destination:
        server: "{{.server}}"
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  applications:
    - name: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: "4.12.0"
      namespace: ingress-nginx
      valuesPath: values

    - name: minio
      repoURL: https://charts.min.io/
      chart: minio
      version: "8.0.0"
      namespace: minio
      valuesPath: values

    - name: velero
      repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: "3.1.0"
      namespace: velero
      valuesPath: values
