apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-addons
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - clusterName: sahand
                  server: "https://vip.sahand.mecan.ir:6443"
                - clusterName: dena
                  server: "https://vip.dena.mecan.ir:6443"
          - list:
              elements:
                - name: ingress-nginx
                  repoURL: https://kubernetes.github.io/ingress-nginx
                  chart: ingress-nginx
                  version: "4.12.0"
                  namespace: ingress-nginx
                - name: minio
                  repoURL: https://charts.min.io/
                  chart: minio
                  version: "8.0.0"
                  namespace: minio
                - name: velero
                  repoURL: https://vmware-tanzu.github.io/helm-charts
                  chart: velero
                  version: "3.1.0"
                  namespace: velero
  template:
    metadata:
      name: "{{clusterName}}-{{name}}"
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}"
        chart: "{{chart}}"
        targetRevision: "{{version}}"
        helm:
          valueFiles:
            - values/{{clusterName}}/{{name}}-values.yaml
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true