name: minio

volumes:
  minio1_data1:
    name: minio1_data1
  minio1_data2:
    name: minio1_data2
  minio1_data3:
    name: minio1_data3
  minio1_data4:
    name: minio1_data4
  minio2_data1:
    name: minio2_data1
  minio2_data2:
    name: minio2_data2
  minio2_data3:
    name: minio2_data3
  minio2_data4:
    name: minio2_data4
  minio3_data1:
    name: minio3_data1
  minio3_data2:
    name: minio3_data2
  minio3_data3:
    name: minio3_data3
  minio3_data4:
    name: minio3_data4
  minio4_data1:
    name: minio4_data1
  minio4_data2:
    name: minio4_data2
  minio4_data3:
    name: minio4_data3
  minio4_data4:
    name: minio4_data4

networks:
  app_net:
    name: app_net
    external: true

services:
  minio1:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio1
    volumes:
      - minio1_data1:/data1
      - minio1_data2:/data2
      - minio1_data3:/data3
      - minio1_data4:/data4
    environment:
      MINIO_ROOT_USER: KWaMp7NwuTpWPWeJ
      MINIO_ROOT_PASSWORD: GRTgwNiDi8HA1m5mz4sdewKWaMp7NwuTpWPWeJ
    command: server http://minio{1...4}/data{1...4} --console-address ":9001"
    networks:
      - app_net
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio2
    volumes:
      - minio2_data1:/data1
      - minio2_data2:/data2
      - minio2_data3:/data3
      - minio2_data4:/data4
    environment:
      MINIO_ROOT_USER: KWaMp7NwuTpWPWeJ
      MINIO_ROOT_PASSWORD: GRTgwNiDi8HA1m5mz4sdewKWaMp7NwuTpWPWeJ
    command: server http://minio{1...4}/data{1...4} --console-address ":9001"
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio3
    volumes:
      - minio3_data1:/data1
      - minio3_data2:/data2
      - minio3_data3:/data3
      - minio3_data4:/data4
    environment:
      MINIO_ROOT_USER: KWaMp7NwuTpWPWeJ
      MINIO_ROOT_PASSWORD: GRTgwNiDi8HA1m5mz4sdewKWaMp7NwuTpWPWeJ
    command: server http://minio{1...4}/data{1...4} --console-address ":9001"
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio4
    volumes:
      - minio4_data1:/data1
      - minio4_data2:/data2
      - minio4_data3:/data3
      - minio4_data4:/data4
    environment:
      MINIO_ROOT_USER: KWaMp7NwuTpWPWeJ
      MINIO_ROOT_PASSWORD: GRTgwNiDi8HA1m5mz4sdewKWaMp7NwuTpWPWeJ
    command: server http://minio{1...4}/data{1...4} --console-address ":9001"
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3