---
apiVersion: v1
data:
  auth: TWVDYW46JGFwcjEkVHFmTzY4ckUkZDhGNHFlMXRqaVRjd0dhZEhuVTJDMQoK
kind: Secret
metadata:
  name: alertmanager-auth
  namespace: monitoring
type: Opaque
---
apiVersion: v1
data:
  auth: TWVDYW46JGFwcjEkVHFmTzY4ckUkZDhGNHFlMXRqaVRjd0dhZEhuVTJDMQoK
kind: Secret
metadata:
  name: prometheus-auth
  namespace: monitoring
type: Opaque

# User: MeCan
# Pass: QsfsfyzwefwsdfwefereLVscTM9WykKergfergergzPqsdsffHD
# Command: htpasswd -nbm MeCan QsfsfyzwefwsdfwefereLVscTM9WykKergfergergzPqsdsffHD | base64