apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  ports:
  - name: "vote-service"
    port: 80
    targetPort: 80
  selector:
    app: vote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  replicas: {{ .Values.spec.vote.replicas }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      imagePullSecrets:
      - name: registry-login
      containers:
      - image: {{ .Values.spec.vote.image }}
        name: vote
        ports:
        - containerPort: 80
          name: vote
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.spec.general.ClusterIssuer }}
    certmanager.k8s.io/acme-http01-edit-in-place: "false"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: vote-ingress
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  ingressClassName: {{ .Values.spec.general.ingressClassName }}
  rules:
  - host: {{ .Values.spec.vote.domain }}
    http:
      paths:
      - backend:
          service:
            name: vote
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.spec.vote.domain }}
    secretName: vote-tls-secret
