apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-priority
  labels:
    env: test
spec:
  containers:
  - name: sample-pod-priority
    image: ahmadrafiee/mecan-sample-app:ver1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 10Mi
        cpu: 10m
      limits:
        memory: 20Mi
        cpu: 20m
  priorityClassName: high-priority