apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: mecan-sample-app
    image: ahmadrafiee/mecan-sample-app:ver1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 10Mi
        cpu: 10m
      limits:
        memory: 20Mi
        cpu: 20m
  nodeSelector:
    disktype: ssd