services:
  backend:
    build:
      context: backend
      target: dev-envs
    restart: always
    secrets:
      - db-password
    depends_on: ['db']
    environment:
      - ASPNETCORE_URLS=http://+:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mariadb:10-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on: 
      - backend

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
