apiVersion: v1
kind: Service
metadata:
  name: voting-app-db
  labels:
    app: voting-app
    component: database
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
  selector:
    app: voting-app
    component: database
