apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate
  annotations:
    kubernetes.io/change-cause: ver2
spec:
  selector:
    matchLabels:
      app: recreate
  replicas: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: recreate
        svc: example
    spec:
      containers:
        - name: hello-world
          image: ahmadrafiee/mecan-sample-app:ver1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m