# syntax=docker/dockerfile:1
FROM golang:1.23 AS build
WORKDIR /src
COPY <<EOF ./main.go
package main

import "fmt"

func main() {
  fmt.Println("hello, world")
}
EOF
RUN go build -o /bin/hello ./main.go

FROM scratch
#COPY --from=0 /bin/hello /bin/hello
COPY --from=build /bin/hello /bin/hello

CMD ["/bin/hello"]


# docker build -t hello .
# The following command assumes you are using the previous Dockerfile but stops at the stage named build:
# docker build --target build -t hello .