apiVersion: v1
kind: Pod
metadata:
  name: mecan-sample-app-pod
  labels:
    app: mecan-sample-app
spec:
  containers:
    - name: main
      image: ahmadrafiee/mecan-sample-app:ver1
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 20Mi
          cpu: 20m