apiVersion: v1
kind: Pod
metadata:
  name: nodeselector
spec:
  containers:
    - name: hello
      image: ahmadrafiee/mecan-sample-app:ver1
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 20Mi
          cpu: 20m
  nodeSelector:
    size: small
